In [2]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [1]:
import pandas as pd
import numpy as np
import json
import re

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.snowball import SnowballStemmer

import warnings
warnings.filterwarnings('ignore')

# Intent Classification

In [2]:
with open('data/data.json') as f:
        data = json.load(f)

In [3]:
for i in range(len(data)):
  examples = data['rasa_nlu_data']['common_examples']

In [4]:
examples[3]['text']

'hey there'

In [5]:
text = [ ]
for i in range(len(examples)):
  text.append(examples[i]['text'])

In [6]:
examples[2]['intent']

'greet'

In [7]:
text

['Hello',
 'Hi',
 'hey',
 'hey there',
 'What is the fellowship program?',
 'How long is the fellowship program?',
 'How much does fellowship program cost?',
 'Can the fellowship program be done remotely?',
 'How do i reach to bridgelabz',
 'What is the working hours of the training program?',
 'How do I get in?',
 'How do I register for the fellowship program?',
 'Do fellowship program offer any stipend or living accommodations?',
 'Do fellowship program offer any package or living accommodations?',
 'What is the minimum qualification for the fellowship program?',
 'What can I expect in the technical interview?',
 'What can fellowship engineer expect in the technical interview?',
 'What happens to fellows after they graduate?',
 'How much package I get after the fellowship program?',
 'What will be my starting salary?',
 'What type of projects will the fellowship engineers get a chance to work on?',
 'What does the day-to-day look like?',
 'What percentage of the fellowship is develop

In [8]:
intents = [ ]
for i in range(len(examples)):
  intents.append(examples[i]['intent'])


In [9]:
intents

['greet',
 'greet',
 'greet',
 'greet',
 'information',
 'details',
 'details',
 'details',
 'details',
 'details',
 'hiringprocess',
 'hiringprocess',
 'details',
 'details',
 'hiringdetails',
 'hiringdetails',
 'hiringdetails',
 'information',
 'details',
 'details',
 'projects',
 'information',
 'details',
 'details',
 'details',
 'details',
 'details',
 'details',
 'details',
 'details',
 'details',
 'hiringprocess',
 'details',
 'details',
 'details',
 'details',
 'hiringdetails',
 'good bye',
 'good bye',
 'good bye',
 'good bye',
 'good bye',
 'Affirmative',
 'Affirmative']

In [10]:
lb = LabelEncoder()
Y = lb.fit_transform(intents)

In [11]:
Y

array([3, 3, 3, 3, 6, 1, 1, 1, 1, 1, 5, 5, 1, 1, 4, 4, 4, 6, 1, 1, 7, 6,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 4, 2, 2, 2, 2, 2, 0, 0])

In [12]:
data = pd.DataFrame(text)

In [13]:
data.head()

0
0                            Hello
1                               Hi
2                              hey
3                        hey there
4  What is the fellowship program?

In [14]:
corpus = [ ]
for i in range(len(data)):
  text = re.sub('[^a-z,A-Z]',  ' ', data[0][i])
  text = text.lower()
  text = word_tokenize(text)
  stemmer = SnowballStemmer('english')
  stop_words = stopwords.words('english')
  text = [stemmer.stem(w) for w in text if w not in stop_words]
  text = ' '.join(text)

  corpus.append(text)

In [15]:
corpus

['hello',
 'hi',
 'hey',
 'hey',
 'fellowship program',
 'long fellowship program',
 'much fellowship program cost',
 'fellowship program done remot',
 'reach bridgelabz',
 'work hour train program',
 'get',
 'regist fellowship program',
 'fellowship program offer stipend live accommod',
 'fellowship program offer packag live accommod',
 'minimum qualif fellowship program',
 'expect technic interview',
 'fellowship engin expect technic interview',
 'happen fellow graduat',
 'much packag get fellowship program',
 'start salari',
 'type project fellowship engin get chanc work',
 'day day look like',
 'percentag fellowship develop real world app',
 'tool get chanc learn',
 'tool fellowship engin get chanc learn',
 'much time take complet fellowship program',
 'need pay fellowship program',
 'durat fellowship program',
 'tool get chanc work',
 'tool fellowship engin get chanc work',
 'train held',
 'get admiss train program',
 'work hour train program',
 'get live accommod',
 'reloc option

In [16]:
len(corpus)

44

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer()

In [19]:
X = cv.fit_transform(corpus).toarray()

In [20]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [21]:
X.shape, Y.shape

((44, 69), (44,))

In [22]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size = 0.2, 
                                                   random_state = 0)

In [23]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((35, 69), (9, 69), (35,), (9,))

In [24]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

In [25]:
classifier = SVC()
classifier.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [26]:
parameters = [{'C': [1,10,100, 1000], 'kernel': ['linear']},
             {'C' : [1,10,100,1000], 'kernel': ['rbf'], 'gamma' : [0.5, 0.1, 0.01, 0.001]}]

grid_search = GridSearchCV(estimator = classifier,
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv = 4,
                          n_jobs = -1)

In [27]:
grid_search = grid_search.fit(x_train, y_train)

In [28]:
grid_search.best_params_


{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}

In [29]:
best_score = grid_search.best_score_

In [30]:
best_score

0.7142857142857143

In [31]:
optimized_classifier = SVC(kernel = 'rbf',
                           C = 10,
                           gamma = 0.1,
                           probability = True)

In [32]:
optimized_classifier.fit(x_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [33]:
y_pred = optimized_classifier.predict(x_test)

In [34]:
y_pred

array([1, 2, 1, 1, 1, 1, 1, 1, 2])

In [35]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           1       0.57      1.00      0.73         4
           2       1.00      1.00      1.00         2
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1

    accuracy                           0.67         9
   macro avg       0.39      0.50      0.43         9
weighted avg       0.48      0.67      0.55         9



In [36]:
y_test

array([1, 2, 1, 6, 5, 1, 1, 5, 2])

In [37]:
actual_output = lb.inverse_transform(y_pred)

In [38]:
actual_output

array(['details', 'good bye', 'details', 'details', 'details', 'details',
       'details', 'details', 'good bye'], dtype='<U13')

# Pipeline for Intent Classification

In [39]:
from sklearn.pipeline import Pipeline

In [40]:
x_train_pip, x_test_pip, y_train_pip, y_test_pip = train_test_split(X,
                                                                    Y,
                                                                    test_size = 0.2,
                                                                    random_state = 0)

In [41]:
print(x_train_pip.shape, y_train_pip.shape)
print(x_test_pip.shape, y_test_pip.shape)

(35, 69) (35,)
(9, 69) (9,)


# Creating a pipeline

In [42]:
steps = [('SVM', SVC())]
pipeline = Pipeline(steps) # definining the pipeline object.

# Grid Search

In [43]:
parameters = [{'SVM__C': [1,10,100, 1000], 'SVM__kernel': ['linear']},
             {'SVM__C' : [1,10,100,1000], 'SVM__kernel': ['rbf'], 'SVM__gamma' : [0.5, 0.1, 0.01, 0.001]}]

grid_search = GridSearchCV(pipeline,
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv = 4,
                          n_jobs = -1)

In [44]:
grid_search.fit(x_train_pip, y_train_pip)

GridSearchCV(cv=4, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('SVM',
                                        SVC(C=1.0, cache_size=200,
                                            class_weight=None, coef0=0.0,
                                            decision_function_shape='ovr',
                                            degree=3, gamma='auto_deprecated',
                                            kernel='rbf', max_iter=-1,
                                            probability=False,
                                            random_state=None, shrinking=True,
                                            tol=0.001, verbose=False))],
                                verbose=False),
             iid='warn', n_jobs=-1,
             param_grid=[{'SVM__C': [1, 10, 100, 1000],
                          'SVM__kernel': ['linear']},
                         {'SVM__C': [1, 10, 100, 1000],
                         

# Checking The accuracy

In [48]:
score = grid_search.score(x_test_pip,y_test_pip)

In [49]:
score

0.6666666666666666

# Getting the predictions obtained using grid search

In [54]:
grid_search.best_estimator_

Pipeline(memory=None,
         steps=[('SVM',
                 SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
                     decision_function_shape='ovr', degree=3, gamma=0.1,
                     kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [50]:
pred = grid_search.best_estimator_.predict(x_test_pip)

In [51]:
pred

array([1, 2, 1, 1, 1, 1, 1, 1, 2])

In [52]:
predictions = lb.inverse_transform(pred)

In [53]:
predictions

array(['details', 'good bye', 'details', 'details', 'details', 'details',
       'details', 'details', 'good bye'], dtype='<U13')